name: Observer
version: ${project.version}
main: masa3mc.observer.Observer
api-version: 1.16
commands:
  ob:
    usage: /ob [player name]
    description: open gui
  Observer:
    usage: /Observer [player name]
    description: open gui
